#!/usr/bin/sh

# простая напоминалка v0.2 ¤ 2018@grayich
# WTFPL

function help {
	name=$(basename $0)
	cat <<EHELP
Простая напоминалка по таймеру

Использование:  ${name} время [сообщение]
  время по умолчанию в секундах
  суффиксы времени: s-секунды, m-минуты, h-часы, d-дни

Примеры:
  ${name} 10 время вышло \\\nблабла бла
  ${name} 15m пиу пиу <b>время</b> <u>вышло</u>
EHELP
}

if [ -n "$1" ]
then
	reg="^[0-9]+[smhd]{0,1}$"
	if ! [[ $1 =~ $reg ]]
	then
		echo "Неправильно задано время: $1"
		echo ... 
		exit 22
	fi

	suf=$(echo $1|sed 's/.*\([smhd]\)$/\1/')
	itime=$(echo $1|sed 's/[^0-9]//g')

	case $suf in
		m) suff="минут";;
		h) suff="часов";;
		d) suff="дней";;
		*) suff="секунд";;
	esac

else
	help
	exit 1
fi

tmr=$1
if [ -n "$2" ]
then
	msg=$(echo $@|cut -d ' ' -f 2-)
fi

echo "Принято, $itime $suff"
echo "-> $msg"

(sleep $tmr; notify-send "$itime $suff прошло" "$msg" -i important -u critical)&

exit 0

